# Generated by Django 4.0.5 on 2022-07-25 19:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0013_posteo_autor_posteo_subtitulo_alter_posteo_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='posteo',
            name='subtitulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
