# Generated by Django 4.0.5 on 2022-07-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0015_delete_curso_delete_entregable_delete_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
