# Generated by Django 4.0.5 on 2022-07-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0016_alter_posteo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo',
            field=models.CharField(max_length=30),
        ),
    ]
